name: Build and Upload Blender Addon Release ZIP

on:
  # This workflow runs when a GitHub release is published.
  release:
    types: [published]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prepare the proper folder structure for the Blender addon.
      # Here we copy the addon folder (currently named "claymode-1.3")
      # to a new folder (named "claymode") so that the ZIP file,
      # when extracted, contains a single folder "claymode" with your files.
      - name: Prepare Blender Addon Folder
        run: |
          # (Adjust these names if your repository layout differs)
          cp -r claymode-1.3 claymode
          # Verify the new folder structure (optional debugging)
          ls -l

      # Create the release ZIP.
      - name: Create Release ZIP
        run: |
          # This zips the "claymode" folder so that the archive has a single top-level folder.
          zip -r clay_mode.zip claymode

      # Upload the ZIP file as an asset of the release.
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clay_mode.zip
          asset_name: clay_mode.zip
          asset_content_type: application/zip
