# Build a release containing a filtered .zip of the repository contents
# when a new semantic version tag is pushed (e.g. v1.0.0).
name: Build Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository into a subdirectory
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      # 2. Zip the repository folder (this creates a zip with an outer folder matching your repository name,
      # which should match the add-on package name expected by Blender)
      - name: Zip Repository (excludes .git*)
        run: |
          cd ${{ github.event.repository.name }}
          zip -r ../${{ github.event.repository.name }}.zip . -x "*.git*"

      # 3. Create a GitHub release using the official action
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 4. Upload the zip file as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
