# Build a release containing a filtered .zip of the repository contents
# when a new semantic version tag is pushed (e.g. v1.2.3).
name: Build Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository under a subdirectory
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      # 2. Zip the repository contents (excluding .git and related files)
      - name: Zip Repository (excludes .git*)
        run: |
          zip -r ${{ github.event.repository.name }}.zip \
            ${{ github.event.repository.name }} \
            -x "${{ github.event.repository.name }}/.git*"

      # 3. Create a GitHub release and attach the zip file
      - name: Create versioned build with filtered zip file
        run: |
          cd ${{ github.event.repository.name }}
          gh release create ${{ github.ref_name }} --generate-notes \
            ../${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
