name: Build Release ZIP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          mkdir clay_mode_addon
          cp -r * clay_mode_addon
          zip -r clay_mode_addon.zip clay_mode_addon

      - name: Upload release ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: clay_mode_addon.zip